import type { ScanReport } from '../types';

/**
 * Prompt only (no issue JSON). User attaches report.json from Download JSON / Save reports.
 */
export function buildAiFixPrompt(report: ScanReport): string {
  const fromLine =
    report.mode === 'module'
      ? `This is a Hugo module/theme package (no trago.js). Migrate it to Hugo ${report.targetVersion}.`
      : `This is a Regular Hugo site. Migrate from Hugo ${report.currentVersion} to Hugo ${report.targetVersion}.`;

  return `You are a senior Hugo migration engineer. Apply ALL fixes from the attached Hugo Assistant report.json in one pass.

${fromLine}

## Input you will receive
- This prompt
- The project's source files in the workspace
- report.json generated by Hugo Assistant (Download JSON or Save .hugo-assistant reports)

Do not ask the user to paste JSON into chat if they already attached/uploaded report.json.

## Goal
Update the local project so it is compatible with Hugo ${report.targetVersion}. Prefer real file edits over explanations. Do not ask follow-up questions unless a cited path is missing from the workspace.

## How to work (token-efficient, one shot)
1. Read report.json once. Use results.structureIssues and results.commonIssues (or equivalent issue lists) as the full required backlog.
2. Deduplicate by rule: if many files share the same structure change (e.g. layouts/partials → layouts/_partials), rename/move in bulk, then update references.
3. For each issue:
   - Open file (and line when present).
   - Apply replacement / fix using title, description, replacement, and documentation.
   - Keep behavior the same unless the Hugo API requires a change.
4. Do structure issues first (renames/moves), then code/config deprecations.
5. After edits, briefly list: files renamed/moved, files edited, anything you could not safely change.

## Rules
- Follow official Hugo docs links in the report when present.
- Do not invent unrelated refactors, formatting-only diffs, or dependency upgrades.
- Do not remove features to “silence” errors; migrate them.
- If replacement is a path (e.g. layouts/_partials), rename/move and update partial/shortcode lookups.
- If replacement is template/config code (e.g. site.Params), replace deprecated usage at the cited location.
- Preserve i18n, assets, and data behavior.

Start migrating now using the workspace files and the attached report.json.`;
}

export async function copyTextToClipboard(text: string): Promise<void> {
  if (navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }

  const ta = document.createElement('textarea');
  ta.value = text;
  ta.setAttribute('readonly', '');
  ta.style.position = 'fixed';
  ta.style.left = '-9999px';
  document.body.appendChild(ta);
  ta.select();
  document.execCommand('copy');
  document.body.removeChild(ta);
}
